### ISSUE TITLE
Mimic MS AD LDAP resultset size of 1000 entries

### ISSUE THREAD

**Issue by 3XC1T3D** [smblds/smblds-container#15]
Hi,

is there a possibility to mimic the MS AD LDAP resultset size of maximum 1000 entries in a ldap search?

best regards

**Comment by robert-scheck** [comment]
If I get you correctly, you are not referring to the `ldap page size` setting in `smb.conf` (which is already 1000 since Samba 4.4), but to the overall LDAP result size? Honestly, I'm not aware about such a limit or setting (even not in Microsoft ADS; could you maybe provide an official reference?), because the typical limit related to 1000 there is the before mentioned LDAP page size.

See also: https://learn.microsoft.com/en-us/windows/win32/adsi/retrieving-large-results-sets

Given this project just uses the latest Samba version, whatever Samba supports is somehow possible. But if you are looking for how to achieve a very special Samba configuration, you might better contact the Samba project directly, sorry.

**Comment by 3XC1T3D** [comment]
Hi @robert-scheck ,

thank you for your reply. A MS AD throws an error when you are requesting more than 1000 entries at once.

We wanted to receive this error. but yeah you are right. we did a little bit research and Samba doesnt support such kind of limiting.

Thank you any way :)

**Comment by robert-scheck** [comment]
@3XC1T3D, how do I achieve such an error with Microsoft AD using e.g. `ldapsearch`?

**Comment by 3XC1T3D** [comment]
you can achieve it, when your using an ldap client which doesnt use pagination. That means a Client which request all users from the ms ad at once (without paging for example 1000 per request)

Newer librarys support pagination, but that library we are using, doesnt support it. So we where searching a possibility to achieve that error, to create a work arround when the error is thrown.

**Comment by robert-scheck** [comment]
Thank you for providing details, nevertheless I didn't manage to reproduce the scenario based on the tools and systems I have access to. I guess for the future it could make sense to update the library to support pagination, even you might dislike this suggestion.
