### ISSUE TITLE
Can't run ldapmodify from customization script

### ISSUE THREAD

**Issue by dolzenko** [smblds/smblds-container#5]
Currently customization scripts (placed in `/entrypoint.d/` volume) run before Samba starts, but that means one can't use e.g.`ldapmodify` from such a script (it expects running server). It appears as one can use `ldbmodify` (from `ldb-tools` package) to modify the database directly. So my question is - would you consider adding this to your image? Seems like a useful addition since many manuals online provide examples on how to use `ldbmodify` to update Samba database. On other hand we can probably provide another mountpoint for scripts to run after the Samba is started.

**Comment by robert-scheck** [comment]
I've added the `ldb-tools` for now, because extending the entrypoints needs reworking of the current concept where `samba` is no longer the main container process. Additionally, even if `samba` is started, the LDAP ports might not be available immediately, but slightly delayed (which requires another hack).

Feel free to let me know in case an entrypoint after `samba` startup gets mandatory. But keep also in mind that the container ships an SSH daemon to allow foreign containers triggering fancy commands and scripts from outside whenever needed.

**Comment by dolzenko** [comment]
Awesome, thank you!

**Comment by dolzenko** [comment]
Minor, but thought I would mention, for ldbmodify to function I had to pass `LDB_MODULES_PATH=/usr/lib/samba/ldb` to it, otherwise it was failing with `WARNING: Module [samba_dsdb] not found - do you need to set LDB_MODULES_PATH?` message

**Comment by robert-scheck** [comment]
I was unable to reproduce this myself, even the Internet confirms that this error message can be raised easily. Could you try whether `LDB_MODULES_PATH="/usr/lib/ldb/modules/ldb:/usr/lib/samba/ldb" ldbmodify …` works for you as expected?

**Comment by robert-scheck** [comment]
I finally have been able to reproduce the error using `ldbsearch` and added wrapper scripts (like for `ldapsearch`).

**Comment by dolzenko** [comment]
Stellar, sorry, just got back to it, I owe you a 🍺 or something :)
